- id: tox-toml-fmt
  name: tox-toml-fmt
  description: ""
  entry: tox-toml-fmt
  language: python
  "files": (^|/)tox\.toml$
  args: []
  require_serial: false
  additional_dependencies: []
  minimum_pre_commit_version: "0"
